# typed: true
def foo; end;
next(foo) # error: No `do` block around `next`
